blogWebsite/blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('post/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new/',views.CreatePostView.as_view(),name='post_new'),
    path('post/<int:pk>/edit',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/remove',views.PostDeleteView.as_view(),name='post_remove'),
    path('post/drafts/',views.DraftListView.as_view(),name='post_draft_list'),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment_to_post'),
    path('comment/<int:pk>/approve/',views.comment_approve,name='comment_approve'),
    path('comment/<int:pk>/remove/',views.comment_remove,name='comment_remove'),
    path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),

]

blogWebsite/blogWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('user/',include('login_user_module.urls')),
    path('accounts/login/',views.LoginView.as_view(), name='login'),
    path('accounts/logout/',views.LogoutView.as_view(),name='logout'),

]

blogWebsite/login_user_module/urls.py
from django.urls import path
from login_user_module import views
from django.contrib.auth import views as djangoView


app_name = 'login_user_module'

urlpatterns = [
    path('register/',views.register, name= 'register'),
    path('logout/',views.logout, name='logout_user')
]

blogWebsite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    #Superuser creates the post
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        #go back to this page once user completes the post
        return reverse("post_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post',related_name='comments',on_delete=models.CASCADE)
    #anyone can comment
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        #go back to this page once user post the comment
        return reverse("post_list")

    def __str__(self):
        return self.text

blogWebsite/login_user_module/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #additional fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank=True)

    def __str__(self):
        return self.user.username

blogWebsite/blog/forms.py
from django import forms
from blog.models import Post,Comment

class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('title','text')
        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass','size':30}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author','text')

        widgets = {
        'author':forms.TextInput(attrs={'class':'textinputclass','size':30}),
        'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

blogWebsite/login_user_module/forms.py
from django import forms
from django.contrib.auth.models import User
from login_user_module.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

blogWebsite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView, ListView, DetailView,
    CreateView, UpdateView, DeleteView
)

from blog.models import Post, Comment
from blog.forms import PostForm,CommentForm


class AboutView(TemplateView):
    template_name = 'about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post

class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

    def form_valid(self, form):
        f = form.save(commit=False)
        f.author = self.request.user
        f.save()
        return redirect('post_detail',pk=f.pk)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class PostDeleteView(LoginRequiredMixin,DeleteView):
    #login_url = '/login/'
    success_url = reverse_lazy('post_list')
    model = Post

class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Post
    redirect_field_name = 'blog/post_draft_list.html'
    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-created_date')


############ Comment ################


@login_required
def post_publish(request,pk):
    post= get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('post_detail',pk=pk)

# Anyone can add comment as a visitor
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if (form.is_valid()):
            comment = form.save(commit = False)
            comment.post = post
            comment.save()
            return redirect('post_list')
            #return redirect('post_detail',pk=post.pk)
    else:
        form = CommentForm()
    return render(request,'blog/comment_form.html',{'form':form})


@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('post_detail',pk=comment.post.pk)


@login_required
def comment_remove(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail',pk=post_pk)

blogWebsite/login_user_module/views.py
from django.shortcuts import render
from login_user_module.forms import UserForm, UserProfileInfoForm

from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'login_user_module/registration.html',{'user_form':user_form,
            'profile_form':profile_form,'registered':registered })

def logout(request):
    return render(request,'login_user_module/logged_out.html')

blogWebsite/blog/templates/blog/about.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

{% block content %}

<div class="jumbocontent">

<div class="jumbotron">

  <h1>About Us</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <h3>Thanks for visiting</h3>


</div>

</div>

{% endblock %}

blogWebsite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static  %}
<html lang="en" dir="ltr">
  <head>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Medium Style Editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Gayathri&display=swap">


    <meta charset="utf-8">
    <title></title>
  </head>
  <body class="format-body">

    <nav class="navbar navbar-default custom-navbar loader techfont">

      <div class="container">

        <ul class="nav navbar-nav">

        <li> <a class="navbar-brand bigbrand" href="{% url 'post_list' %}">Blog</a> </li>
        <li> <a class="nav-text" href="{% url 'about' %}">About</a> </li>
        <li> <a class="nav-text" href="https://www.github.com">GitHub</a> </li>
        <li> <a class="nav-text" href="https://www.linkedin.com">LinkedIn</a> </li>

        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li> <a class="nav-text" href="{% url 'post_new' %}">New Post</a> </li>
          <li> <a class="nav-text" href="{% url 'post_draft_list' %}">Drafts</a> </li>
          <li> <a class="nav-text" href="{% url 'logout' %}">Logout</a> </li>
          <li> <a class="nav-text" >Welcome {{user.username}}</a> </li>

          {% else %}
          <li> <a class="nav navbar-right nav-text" href="{% url 'login' %}">Login <span class="glyphicon glyphicon-user"></span> </a> </li>
          <li> <a class="nav navbar-right nav-text" href="{% url 'login_user_module:register' %}">Sign Up</a> </li>

          {% endif %}
        </ul>

      </div>

    </nav>

    <div class="content container">
      <div class="row  format-content">
          <div class="col-md-8">
            <div class="blog_posts">
              {% block content %}

              {% endblock %}
            </div>
          </div>
      </div>
    </div>

  </body>
</html>

blogWebsite/blog/templates/blog/comment_form.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

{% block content %}

<h2>New Comment</h2>
<br>
<form class="post-form"  method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" id="savebutton" class="save btn btn-success">Post</button>
  <a class="btn btn-danger" href="{% url 'post_draft_list' %}">Cancel</a>
</form>

<script>
  var editor = new MediumEditor('.editable');
</script>

{% endblock %}

blogWebsite/blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    <h4>Are you sure, you want to delete: {{object}} ?</h4>
    <input type="submit" class="btn btn-danger" value="Delete">
  </form>

{% endblock %}

blogWebsite/blog/templates/blog/post_detail.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

{% block content %}

<h1 class="posttitle">{{post.title}}</h1>
{% if post.published_date %}
  <div class="date postdate">
    {{post.published_date}}
  </div>
{% else %}
  <div class="date postdate">
    <p>Created On: {{post.created_date}}</p>
  </div>
  <br>

  <a class="btn btn-info" href="{% url 'post_publish' pk=post.pk %}">Publish</a>
{% endif %}

<div class="date author">
  <p>Author: {{post.author}}</p>
</div>


<p class="postcontent">{{post.text|safe|linebreaksbr}}</p>
<br>
{% if user.is_authenticated %}
{% ifequal user.username post.author.username %}
  <a class="btn btn-primary" href="{% url 'post_edit' pk=post.pk %}"> <span class="glyphicon glyphicon-pencil"></span></a>
  <a class="btn btn-danger" href="{% url 'post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-trash"></span></a>
{% endifequal %}
{% endif %}

<hr>
<a class="btn btn-info btn-comment" href="{% url 'add_comment_to_post' pk=post.pk %}">Add Comment</a>

<div class="container">
  <br>
    <br>
    {% for comment in post.comments.all %}

      {% if comment.approved_comment %}
        {{comment.created_date}}
        <p>{{comment.text|safe|linebreaksbr}}</p>
        <p>Posted By: {{comment.author}}</p>
        <br>
      {% endif %}

      {% if user.is_authenticated  and not comment.approved_comment %}
      {% ifequal user.username post.author.username %}
        {{comment.created_date}}
        <a class="btn btn-success" href="{% url 'comment_approve' pk=comment.pk %}"> <span class="glyphicon glyphicon-ok"></span></a>
        <a class="btn btn-danger" href="{% url 'comment_remove' pk=comment.pk %}"> <span class="glyphicon glyphicon-trash"></span></a>
        <p>{{comment.text|safe|linebreaksbr}}</p>
        <p>Posted By: {{comment.author}}</p>
      {% endifequal %}
      {% endif %}

    {% empty %}

    <div class="no-comment">
      <p>No Comments</p>
    </div>

    {% endfor %}

</div>

{% endblock %}

blogWebsite/blog/templates/blog/post_draft_list.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

<!-- DOES NOT WORK -->

{% block content %}

  {% for post in posts %}
    <div class="post_lists">
      <h2> <a class="drafts" href="{% url 'post_detail' pk=post.pk %}">{{post.title}}</a> </h2>
      <p class="date">Created on: {{post.created_date}}</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>{{post.text|safe|linebreaksbr|truncatechars_html:200}}</p>
    </div>
    <div class="floatclass author">
      <h5>Author: {{post.author}} </h5>
    </div>
  {% endfor %}

{% endblock %}

blogWebsite/blog/templates/blog/post_form.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

{% block content %}

<h2>New Post</h2>
<br>
  <form class="post-form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" id="savebutton" class="save btn btn-success" >Save</button>
    <a class="btn btn-danger" href="{% url 'post_draft_list' %}">Cancel</a>
  </form>

<script>
  var editor =  new MediumEditor('.editable');
</script>

{% endblock %}

blogWebsite/blog/templates/blog/post_list.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

{% block content %}

<div class="centerstage">
  {% for post in post_list %}
    <div class="post_lists">

        <!-- Published Posts -->
        {% if post.published_date %}
          <h2> <a href="{% url 'post_detail' pk=post.pk %}"> {{post.title}} </a> </h2>

          <div class="date">
            <p>Published On: {{post.published_date|date:"D d M Y"}}</p>
          </div>
        {% else %}
          <h3> <a id="drafts" href="{% url 'post_detail' pk=post.pk %}"> {{post.title}} </a> </h3>

        <!-- Draft Posts -->
          <div class="date">
            <p>Created On: {{post.created_date|date:"D d M Y"}}</p>
          </div>
        {% endif %}

        <p>{{post.text|safe|linebreaksbr|truncatechars_html:20}}</p>

        <a href="{% url 'post_detail' pk=post.pk %}">Comments: {{post.approve_comments.count}}</a>

        <div class="floatclass author">
          <h5>Author: {{post.author}} </h5>
        </div>
    </div>
    <hr>

  {% empty %}
      <p>No Blogs available</p>

  {% endfor %}

</div>

{% endblock %}

blogWebsite/login_user_module/templates/login_user_module/logged_out.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}

{% block content %}

<div class="jumbocontent">

<div class="jumbotron">

  <h3>Thank You.</h3>
  <p>You have successfully logged out.</p>

  <a href="{% url 'post_list' %}">Back to Home Page</a>


</div>

</div>

{% endblock %}

blogWebsite/login_user_module/templates/login_user_module/registration.html
<!DOCTYPE html>
{% extends "blog/base.html" %}
{% load static %}

{% block content %}

<div class="jumbotron">
  {% if registered %}
    <h3>Thank you for registering</h3>
    <br>
    <li> <a class="bigbrand" href="{% url 'login' %}">Login <span class="glyphicon glyphicon-chevron-right"></span> </a> </li>
  {% else %}
    <h1>Please register</h1>
    <h3>Fill the form</h3>

    <form enctype="multipart/form-data" method="POST">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}

      <input type="submit"  value="Register">

    </form>
  {% endif %}
</div>

{% endblock %}